_target_: models.forcast.globallstm.GlobalLSTM
model: global-lstm
model_params:
  seq_len: 50
  batch_size: 256
  dropout: 0
  use_mc_dropout: false
  use_with_mdn: true
  train_with_calib: true
  lstm_conf:
    hidden_size: 256
    num_layers: 1
    dropout: 0 # Never use it!
  mdn_conf:
    n_targets: 1
    n_components: 7
  pre_trained_model_path: null
  pre_trained_predictions_paths: null
  plot_eval_after_train: false