_target_: models.forcast.globallstm.GlobalLSTM
model: global-lstm
model_params:
  seq_len: 50
  batch_size: 512
  dropout: 0
  use_mc_dropout: false
  train_with_calib: false
  lstm_conf:
    hidden_size: 128
    num_layers: 1
    dropout: 0 # Never use it!
  pre_trained_model_path: null
  plot_eval_after_train: false