_target_: models.forcast.precomputed_nh.PrecomputedNeuralHydrologyForcast
model: precomputed-nh
model_params:
  nh_results_path: ${config.experiment_data.base_proj_dir}models_save/hydro/neuralhydrology_9y_1601_092104_test_results/test_results.p
  target_variable: 'QObs(mm/d)_sim'