_target_: loader.config.TSDataConfig
dataset_type: solar
paths:
  - /some_base_dir/data/enbPI/Fremont_data.csv
  - /some_base_dir/data/enbPI/Milpitas_data.csv
  - /some_base_dir/data/enbPI/Mountain_View_data.csv
  - /some_base_dir/data/enbPI/Palo_Alto_data.csv
  - /some_base_dir/data/enbPI/Redwood_City_data.csv
  - /some_base_dir/data/enbPI/Santa_Clara_data.csv
  - /some_base_dir/data/enbPI/San_Mateo_data.csv
  - /some_base_dir/data/enbPI/Sunnyvale_data.csv
add_config:
