_target_: loader.config.TSDataConfig
dataset_type: hydro-531_basin_list.txt
paths:
  - /some_base_dir/data/hydrology
add_config:
  nh_config_path: ${config.experiment_data.base_proj_dir}models_save/hydro/config_caltest.yml
  use_static_attributes: True