_target_: loader.config.TSDataConfig
dataset_type: hydro-pub_fold_0.txt
paths:
  - /some_base_dir/data/hydrology
add_config:
  nh_config_path: ${config.experiment_data.base_proj_dir}configuration/hydrology/hydro_eval/cmal/part1/processed/config_1.yml
  use_static_attributes: True
  no_calib: True