_target_: loader.config.TSDataConfig
dataset_type: nsdb-60m-2019
paths:
  - /some_base_dir/data/nsdb_2019/Alachua-Gainesville.csv
  - /some_base_dir/data/nsdb_2019/Alameda-Oakland.csv
  - /some_base_dir/data/nsdb_2019/Albany-Albany2.csv
  - /some_base_dir/data/nsdb_2019/Allegheny-Pittsburgh.csv
  - /some_base_dir/data/nsdb_2019/Bexar-San_Antonio1.csv
add_config:
