_target_: loader.config.TaskConfig
task_type: 'PI'
alpha: [0.01, 0.05, 0.1, 0.15, 0.20, 0.25, 0.3, 0.35]
data_splits: [0.6, 0.15, 0.25] # [0.6, 0.15, 0.25]  #[0.34, 0.33, 0.33]
fc_estimator_mode: single
global_norm: false
add_config:
