_target_: models.uncertainty.sota.bluecat.Bluecat
quantile_mode: empirical # empirical, k-moments
sample_m: 100 # size of m1 and m2
eps_mem_size: 5000
used_calibration_set: calib # calib, train, both
online_memory: true