_target_: models.uncertainty.pi_eps_sel_base.EpsSelectionPIStat
ctx_mode: uni_past_multi_step_and_yhat
sim_mode: pearson
keep_calib_eps: false
eps_mem_size: 300
past_window: 50
no_of_beta_bins: 1
retrieve_mode: sample
topk_used_share: null # Only allowed to set for ktop retrieval
topk_adaptive: null # Only allowed to set for ktop retrieval
online_memory: true