_target_: models.uncertainty.pi_eps_pred_lstm.EpsPredictionLSTM
ctx_mode: uni_past_multi_step_and_yhat_and_tsOneHot
ctx_past_window: 50
keep_calib_eps: false
eps_mem_size: 80
with_loss_weight: 0
coverage_loss_weight: 0
use_pinball_loss: True
chung_loss_weight: 0