_target_: models.uncertainty.pi_eps_pred_hopfield.EpsPredictionHopfield
# Context
ctx_mode: uni_past_multi_step_and_yhat
ctx_past_window: 1
#Context Encode
ctx_encode_hiddenL: 0
ctx_encode_dropout: null
ctx_encode_relu_before_hf: false
history_compress:
  mode: null
  window: null
pos_encode:
  mode: null
  dim: 5
# Memory
keep_calib_eps: false
eps_mem_size: 8000
# Model
hopfield_beta: 1
head_per_alpha: False
eps_to_stored_pattern: False
# Train
batch_size: 4
batch_mode: one_ts
batch_mix_count: null    # Only possible if not one_ts batch mode is used
mix_data_inference_mode: null # Only possible if not one_ts batch mode is used
mix_data_inference_count: 3 # Only used if mix inference used and not mix_all
use_memory_window: False
train_only_past: False
limit_train_seq_to_mem_size: False
limit_train_seq_stride: 10 # Only relevant if limit_train_seq_to_mem_size is True
predict_abs_eps: True
train_alphas: null        # Only possible for Per Head and in Conf Mode with residuals or absolute Loss
sample_alpha_train: null  # Only possible for NOT per Head with absolute or residual loss mode
# Inference Conformal
conf_selection: True
conf_eps_abs: False
conf_sel_beta: 0
mix_head_dist: True
sample_alpha_inference: False  # Only possible for NOT per Head with absolute or residual loss mode
conf_quantile_mode: sample  # cdf, sample, debug
# Loss
loss_mode: mse
with_loss_weight: 0       # with residuals, absolute, mse
coverage_loss_weight: 0   # with residuals
chung_loss_weight: 0      # with residuals
# Adaptive CI
use_adaptiveci: False
gamma: 0.005