### HYDRA START
hydra:
  run:
    dir: ./outputs/${hydra.job.name}
  sweep:
    dir: ./outputs/${hydra.job.name}
    subdir: ${hydra.job.num}
  job:
    chdir: True # change working directory of run
    name: ${config.experiment_data.experiment_name}_${now:%d%m%y_%H%M%S}
#  launcher:
#    n_jobs: 8
#    prefer: processes
#    pre_dispatch: 8  
### HYDRA END

### RUN CONFIG START
run_config:
  exec_type: parallel # sequential
  gpu_ids: [0]
  runs_per_gpu: 1 # Only relevant for parallel execution
  seeds:
     - 10

sweep:
  type: grid
  axes:
    - parameter: model_uc.rho
      vals:
        - 0.90
        - 0.95
        - 0.98
        - 0.99
        - 0.993
        - 0.995
        - 0.999
    - parameter: experiment_data.evaluate
      vals:
       - False
    - parameter: evaluation.pred_vega
      vals:
       - False       
### RUN CONFIG END

###################################
defaults:
  - config: default
#  - override hydra/launcher: joblib
  - override config/model_fc: darts_forest
  - override config/model_uc: nextcp
  - override config/dataset: nsdb2019_60m
  - override config/task: default_1year


config:

  ### EXPERIMENT CONFIG
  experiment_data:
    project_name: null
    project_entity: null
    base_proj_dir: null
    data_dir: ${config.experiment_data.base_proj_dir}data
    model_dir: ${config.experiment_data.base_proj_dir}models_save
    evaluate: true
    offline: disabled
    experiment_tag: tag
    experiment_name: name
    experiment_notes: # str, used to make notes to wandblogger
    experiment_dir: null
    experiment_sweep_fp: null      # This is used by sweep to allow grouping of multiple seeds
    experiment_sweep_tag: NoSweep  # This is used by sweep to allow filter for the sweep
    seed: 10
    gpu_id: 4

  trainer:
    _target_: trainer.internal_trainer.ModelInternalTrainer
    trainer_config:
      n_epochs: 700
      val_every: 5
      save_every: 10000
      early_stopping_patience: 10000
      optim:
        _target_: torch.optim.AdamW
        _partial_: true
        lr: 0.01
        weight_decay: 0.01
      lr_scheduler:
      model_selection: threshold-pi
      init_model: null # NOT USED
  ###
